# -*- coding: utf-8 -*-
"""AI Job (Top 20) .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-SGBqASUhZsRetVWGLAR0v3gvOWguoHm
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load the dataset from the local file
df = pd.read_csv('/content/ai_job_market_insights.csv')

# Print the first few rows of the dataset
print("First few rows of the dataset:")
print(df.head())

# Print the description of the dataset
print("\nDescription of the dataset:")
print(df.info())

# Fill missing values in numerical columns (if any)
numerical_cols = ['Job Ttile (Domain)', 'Salary', 'Industry', 'Required_Skills', 'Job Title']  # Adjust based on actual numerical columns

df[numerical_cols] = df[numerical_cols].fillna(method='ffill')

# Horizontal bar chart for top 20 jobs by salary
plt.figure(figsize=(25, 10))
plt.barh(top_20_jobs['Job Ttile (Domain)'], top_20_jobs['Salary'], color='purple')
plt.xlabel("Salary")
plt.ylabel("Job Title (Domain)")
plt.title('AI Job Market Insights: Top 20 Salary Horizontal Bar Chart')
plt.tight_layout()
plt.show()


# Sort the dataset by 'Salary' for better visualization
df = df.sort_values(by='Salary')
top_20_jobs = df.sort_values(by='Salary', ascending=False).head(20)
plt.figure(figsize=(20, 10))
plt.bar(top_20_jobs['Job Ttile (Domain)'], top_20_jobs['Salary'], color='blue')
plt.xlabel("Job Title (Domain)")
plt.ylabel("Salary")
plt.title('AI Job Market Insights: Top 20 Salary Bar Chart')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

# Analyze the dataset
print("\nSummary statistics of the dataset:")
print(df.describe())

"""Analysis of AI Job Market Insights

1. Data Inspection
The dataset contains various columns, including job titles and salaries. We have filled any missing values in the 'Salary' column using forward fill.

2. Visualizations
  Horizontal Bar Chart:
     Displays the top 20 highest-paying job titles, making it easy to identify high-salary positions.
     
  Vertical Bar Chart:
     Provides a comparative view of salaries for the top 20 job titles.

3. Summary Statistics
The summary statistics provide insights into the overall distribution of salaries and can help identify trends or outliers.

For a detailed interpretation, please refer to the visualizations and statistics provided above.

"""